spring.application.name=digital-health-exercise

server.port=8080

# H2 in-memory DB
#spring.datasource.url=jdbc:h2:file:./data/exercise
spring.datasource.url=jdbc:h2:mem:exercise;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin123
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#execute data.sql file
spring.jpa.defer-datasource-initialization=true

# H2 console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security
app.security.api-key=digital-health-secret-key

